// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0u3YXH2Jmrjwql6pHb9JWXiEu3Wqyho0',
    appId: '1:1010996261324:web:992c8fba8e09bb72e82d69',
    messagingSenderId: '1010996261324',
    projectId: 'emailauut',
    authDomain: 'emailauut.firebaseapp.com',
    storageBucket: 'emailauut.firebasestorage.app',
    measurementId: 'G-VPFJ1GKNKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMk1mWeD9CLZRzYwTHK-bVYK4Bl8EoMKs',
    appId: '1:1010996261324:android:853dc7f9f72f955be82d69',
    messagingSenderId: '1010996261324',
    projectId: 'emailauut',
    storageBucket: 'emailauut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeN51lvwlv8jf8qfR4Kf1geIB55YCkxlo',
    appId: '1:1010996261324:ios:ad40d0581115d3d2e82d69',
    messagingSenderId: '1010996261324',
    projectId: 'emailauut',
    storageBucket: 'emailauut.firebasestorage.app',
    androidClientId: '1010996261324-d03da71cbc8lh8glbd4elhk079duafns.apps.googleusercontent.com',
    iosClientId: '1010996261324-ueki3acia2gafd6cqatspnvsngkqk5h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSigin',
  );

}